### ISSUE TITLE
Call to undefined method Symfony\Component\DomCrawler\Crawler::rewind()

### ISSUE THREAD

**Issue by cornernote** [Blumster/yii2-gii-migration-designer#1]
When I load the page in Gii I get this:

PHP Fatal Error – yii\base\ErrorException

Call to undefined method Symfony\Component\DomCrawler\Crawler::rewind()
1. in .../vendor/wbraganca/yii2-dynamicform/DynamicFormWidget.php

**Comment by Blumster** [comment]
Hi there!

I'm working on the 0.2.0 version, where I don't need the yii2-dynamicform package.

That package is causing the error. My guess is that it (or its dependencies) got outdated. I will push the changes in the next few days and it will work again!

**Comment by Blumster** [comment]
Hey! I had the time to finish it up. I'll release 0.2 soon, update, and tell me if something isn't working! Thanks! :)
